<#
.SYNOPSIS
  Create a local .env file from an existing Azure OpenAI resource and optional Azure service settings.

.DESCRIPTION
  This helper writes a `.env.local` file for local development using an existing
  Azure Cognitive Services OpenAI resource. It does not provision Azure resources.

.PARAMETER ResourceGroupName
  The resource group that contains the OpenAI account.

.PARAMETER OpenAIResourceName
  The Azure Cognitive Services account name.

.PARAMETER OpenAIDeployment
  The OpenAI deployment name in the resource. Default: gpt-4o-mini

.PARAMETER OpenAIAPIVersion
  The Azure OpenAI API version to use. Default: 2024-10-21

.PARAMETER AzureTenantId
  Optional tenant id for Entra ID auth. If omitted, it uses the current Azure login tenant.

.PARAMETER AzureClientId
  Optional Entra app client id for auth.

.PARAMETER AzureClientSecret
  Optional Entra app client secret for auth.

.PARAMETER AzureCosmosConnectionString
  Optional Cosmos DB connection string if you want persistent storage.

.PARAMETER AzureStorageConnectionString
  Optional Storage connection string if you want exports.

.PARAMETER RedirectUri
  Optional redirect URI for OAuth callback. Default: http://localhost:3000/auth/callback

.PARAMETER PublicBaseUrl
  Optional public base URL for local runtime. Default: http://localhost:3000
#>

[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)] [string]$ResourceGroupName,
  [Parameter(Mandatory = $true)] [string]$OpenAIResourceName,
  [string]$OpenAIDeployment = "gpt-4o-mini",
  [string]$OpenAIAPIVersion = "2024-10-21",
  [string]$AzureTenantId = "",
  [string]$AzureClientId = "",
  [string]$AzureClientSecret = "",
  [string]$AzureCosmosConnectionString = "",
  [string]$AzureStorageConnectionString = "",
  [string]$RedirectUri = "http://localhost:3000/auth/callback",
  [string]$PublicBaseUrl = "http://localhost:3000"
)

$ErrorActionPreference = "Stop"

function Require-Cli($name) {
  $cmd = Get-Command $name -ErrorAction SilentlyContinue
  if (-not $cmd) {
    throw "$name is not installed or not on PATH. Install it and retry."
  }
}

Require-Cli az

Write-Host "[1/3] Verifying Azure login..." -ForegroundColor Cyan
$account = az account show --only-show-errors 2>$null | ConvertFrom-Json
if (-not $account) {
  Write-Host "  -> running 'az login'"
  az login | Out-Null
  $account = az account show --only-show-errors | ConvertFrom-Json
}

Write-Host "[2/3] Reading Azure OpenAI resource..." -ForegroundColor Cyan
$endpoint = az cognitiveservices account show -g $ResourceGroupName -n $OpenAIResourceName --query properties.endpoint -o tsv
$openAiKey = az cognitiveservices account keys list -g $ResourceGroupName -n $OpenAIResourceName --query key1 -o tsv
if (-not $endpoint -or -not $openAiKey) {
  throw "Failed to read Azure OpenAI endpoint or key for resource '$OpenAIResourceName' in RG '$ResourceGroupName'."
}

if (-not $AzureTenantId) {
  $AzureTenantId = $account.tenantId
}

Write-Host "[3/3] Writing .env.local..." -ForegroundColor Cyan
$envText = @"
# Generated by scripts/setup-existing-azure.ps1 on $(Get-Date -Format o)
NODE_ENV=development
PORT=3000
PUBLIC_BASE_URL=$PublicBaseUrl

AZURE_OPENAI_ENDPOINT=$endpoint
AZURE_OPENAI_API_KEY=$openAiKey
AZURE_OPENAI_DEPLOYMENT=$OpenAIDeployment
AZURE_OPENAI_API_VERSION=$OpenAIAPIVersion

AZURE_COSMOS_CONNECTION_STRING=$AzureCosmosConnectionString
AZURE_COSMOS_DATABASE=arqcdr-db
AZURE_COSMOS_CONTAINER=projects

AZURE_STORAGE_CONNECTION_STRING=$AzureStorageConnectionString
AZURE_STORAGE_CONTAINER=exports

AZURE_TENANT_ID=$AzureTenantId
AZURE_CLIENT_ID=$AzureClientId
AZURE_CLIENT_SECRET=$AzureClientSecret
AZURE_REDIRECT_URI=$RedirectUri

VITE_AZURE_TENANT_ID=$AzureTenantId
VITE_AZURE_CLIENT_ID=$AzureClientId
VITE_AZURE_REDIRECT_URI=$PublicBaseUrl
"@

$envPath = Join-Path (Resolve-Path "$PSScriptRoot\.." ) ".env.local"
$envText | Set-Content -Path $envPath -Encoding UTF8

Write-Host "Done. .env.local generated from existing Azure OpenAI resource." -ForegroundColor Green
