#!/usr/bin/env bash
# Create .env.local from an existing Azure OpenAI resource and optional Azure service settings.
set -euo pipefail

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <OpenAIResourceName> <ResourceGroupName> [OpenAIDeployment] [OpenAIAPIVersion]"
  echo "Example: $0 ARQCDRGEMGPT ARQCDRGEM gpt-4o-mini 2024-10-21"
  exit 1
fi

OPENAI_RESOURCE_NAME="$1"
RESOURCE_GROUP_NAME="$2"
OPENAI_DEPLOYMENT="${3:-gpt-4o-mini}"
OPENAI_API_VERSION="${4:-2024-10-21}"
AZURE_TENANT_ID="${AZURE_TENANT_ID:-}"
AZURE_CLIENT_ID="${AZURE_CLIENT_ID:-}"
AZURE_CLIENT_SECRET="${AZURE_CLIENT_SECRET:-}"
AZURE_COSMOS_CONNECTION_STRING="${AZURE_COSMOS_CONNECTION_STRING:-}"
AZURE_STORAGE_CONNECTION_STRING="${AZURE_STORAGE_CONNECTION_STRING:-}"
REDIRECT_URI="${AZURE_REDIRECT_URI:-http://localhost:3000/auth/callback}"
PUBLIC_BASE_URL="${PUBLIC_BASE_URL:-http://localhost:3000}"

command -v az >/dev/null 2>&1 || { echo "az CLI is required." >&2; exit 1; }

echo "[1/3] Verifying Azure login..."
az account show >/dev/null 2>&1 || az login

if [ -z "$AZURE_TENANT_ID" ]; then
  AZURE_TENANT_ID=$(az account show --query tenantId -o tsv)
fi

echo "[2/3] Reading Azure OpenAI resource..."
ENDPOINT=$(az cognitiveservices account show -g "$RESOURCE_GROUP_NAME" -n "$OPENAI_RESOURCE_NAME" --query properties.endpoint -o tsv)
OPENAI_KEY=$(az cognitiveservices account keys list -g "$RESOURCE_GROUP_NAME" -n "$OPENAI_RESOURCE_NAME" --query key1 -o tsv)

if [ -z "$ENDPOINT" ] || [ -z "$OPENAI_KEY" ]; then
  echo "Failed to read Azure OpenAI endpoint or key." >&2
  exit 1
fi

cat > .env.local <<EOF
# Generated by scripts/setup-existing-azure.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NODE_ENV=development
PORT=3000
PUBLIC_BASE_URL=$PUBLIC_BASE_URL

AZURE_OPENAI_ENDPOINT=$ENDPOINT
AZURE_OPENAI_API_KEY=$OPENAI_KEY
AZURE_OPENAI_DEPLOYMENT=$OPENAI_DEPLOYMENT
AZURE_OPENAI_API_VERSION=$OPENAI_API_VERSION

AZURE_COSMOS_CONNECTION_STRING=$AZURE_COSMOS_CONNECTION_STRING
AZURE_COSMOS_DATABASE=arqcdr-db
AZURE_COSMOS_CONTAINER=projects

AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING
AZURE_STORAGE_CONTAINER=exports

AZURE_TENANT_ID=$AZURE_TENANT_ID
AZURE_CLIENT_ID=$AZURE_CLIENT_ID
AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET
AZURE_REDIRECT_URI=$REDIRECT_URI

VITE_AZURE_TENANT_ID=$AZURE_TENANT_ID
VITE_AZURE_CLIENT_ID=$AZURE_CLIENT_ID
VITE_AZURE_REDIRECT_URI=$PUBLIC_BASE_URL
EOF

echo "Done. .env.local generated from existing Azure OpenAI resource."
