<#
.SYNOPSIS
  Provision the ARQCdR Azure stack and seed .env.local with the resulting
  endpoints + keys. Designed for Windows PowerShell 5.1+ and PowerShell 7+.

.DESCRIPTION
  Requires:
    - Azure CLI         (`az`)        — login: az login
    - Azure Developer   (`azd`)       — login: azd auth login

  What this script does:
    1. Ensures `az` and `azd` are signed in.
    2. Initializes the azd environment if needed.
    3. Runs `azd up` to deploy Bicep + push the container image.
    4. Reads outputs and writes them into .env.local.

.PARAMETER EnvName
  Azure environment name (e.g. dev, stg, prod). Default: dev

.PARAMETER Location
  Azure region for the resource group. Default: eastus2

.EXAMPLE
  ./scripts/setup-azure.ps1 -EnvName dev -Location eastus2
#>

[CmdletBinding()]
param(
  [string]$EnvName = "dev",
  [string]$Location = "eastus2"
)

$ErrorActionPreference = "Stop"

if ($Location -eq "brazilsouth") {
  Write-Host "[!] brazilsouth may not support the gpt-4o OpenAI deployment. Switching to eastus2 for compatibility." -ForegroundColor Yellow
  $Location = "eastus2"
}

function Require-Cli($name) {
  $cmd = Get-Command $name -ErrorAction SilentlyContinue
  if (-not $cmd) {
    throw "$name is not installed or not on PATH. Install it and retry."
  }
}

Require-Cli az
Require-Cli azd
Require-Cli node

Write-Host "[1/5] Verifying Azure logins..." -ForegroundColor Cyan
$account = az account show --only-show-errors 2>$null | ConvertFrom-Json
if (-not $account) {
  Write-Host "  -> running 'az login'"
  az login | Out-Null
}

azd auth login --check-status 2>$null
if ($LASTEXITCODE -ne 0) {
  Write-Host "  -> running 'azd auth login'"
  azd auth login | Out-Null
}

Write-Host "[2/5] Initializing azd environment '$EnvName'..." -ForegroundColor Cyan
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
Push-Location $repoRoot
try {
  $envList = azd env list --output json 2>$null | ConvertFrom-Json
  if (-not ($envList | Where-Object { $_.Name -eq $EnvName })) {
    azd env new $EnvName --location $Location | Out-Null
  }
  azd env select $EnvName | Out-Null
  azd env set AZURE_LOCATION $Location | Out-Null
  azd env set AZURE_ENV_NAME $EnvName  | Out-Null

  Write-Host "[3/5] Provisioning infrastructure + deploying app..." -ForegroundColor Cyan
  azd up
  if ($LASTEXITCODE -ne 0) { throw "azd up failed." }

  Write-Host "[4/5] Reading deployment outputs..." -ForegroundColor Cyan
  $rgName = (azd env get-values --output json | ConvertFrom-Json).AZURE_RESOURCE_GROUP

  $endpoint    = az cognitiveservices account show -g $rgName -n "arqcdr-openai-$EnvName" --query properties.endpoint -o tsv
  $openAiKey   = az cognitiveservices account keys list -g $rgName -n "arqcdr-openai-$EnvName" --query key1 -o tsv
  $cosmosConn  = az cosmosdb keys list -g $rgName -n "arqcdr-cosmos-$EnvName" --type connection-strings --query "connectionStrings[0].connectionString" -o tsv
  $storageName = "arqcdrst$EnvName"
  $storageKey  = az storage account keys list -g $rgName -n $storageName --query "[0].value" -o tsv
  $storageConn = "DefaultEndpointsProtocol=https;AccountName=$storageName;AccountKey=$storageKey;EndpointSuffix=core.windows.net"

  Write-Host "[5/5] Writing .env.local..." -ForegroundColor Cyan
  $tenantId = $account.tenantId
  $envText = @"
# Generated by scripts/setup-azure.ps1 on $(Get-Date -Format o)
NODE_ENV=development
PORT=3000
PUBLIC_BASE_URL=http://localhost:3000

AZURE_COSMOS_CONNECTION_STRING=$cosmosConn
AZURE_COSMOS_DATABASE=arqcdr-db
AZURE_COSMOS_CONTAINER=projects

AZURE_STORAGE_CONNECTION_STRING=$storageConn
AZURE_STORAGE_CONTAINER=exports

AZURE_OPENAI_ENDPOINT=$endpoint
AZURE_OPENAI_API_KEY=$openAiKey
AZURE_OPENAI_DEPLOYMENT=gpt-4o-mini
AZURE_OPENAI_API_VERSION=2024-10-21

AZURE_TENANT_ID=$tenantId
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=
AZURE_REDIRECT_URI=http://localhost:3000/auth/callback

VITE_AZURE_TENANT_ID=$tenantId
VITE_AZURE_CLIENT_ID=
VITE_AZURE_REDIRECT_URI=http://localhost:3000
VITE_API_BASE=
"@
  $envText | Set-Content -Path (Join-Path $repoRoot ".env.local") -Encoding UTF8

  Write-Host ""
  Write-Host "Done. ARQCdR is provisioned in resource group '$rgName'." -ForegroundColor Green
  Write-Host "Next: register an Entra ID application and fill AZURE_CLIENT_ID / VITE_AZURE_CLIENT_ID in .env.local." -ForegroundColor Yellow
}
finally {
  Pop-Location
}
