#!/usr/bin/env bash
# ARQCdR Azure setup — bash counterpart to scripts/setup-azure.ps1.
# Provisions infra via `azd up` and writes endpoints + keys to .env.local.

set -euo pipefail

ENV_NAME="${1:-dev}"
LOCATION="${2:-eastus2}"

if [ "$LOCATION" = "brazilsouth" ]; then
  echo "[!] brazilsouth may not support the gpt-4o OpenAI deployment. Switching to eastus2 for compatibility."
  LOCATION="eastus2"
fi

require_cli() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing CLI: $1"; exit 1; }
}
require_cli az
require_cli azd
require_cli node

echo "[1/5] Verifying Azure logins..."
az account show >/dev/null 2>&1 || az login
azd auth login --check-status >/dev/null 2>&1 || azd auth login

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "[2/5] Initializing azd environment '$ENV_NAME'..."
if ! azd env list --output json | grep -q "\"$ENV_NAME\""; then
  azd env new "$ENV_NAME" --location "$LOCATION"
fi
azd env select "$ENV_NAME"
azd env set AZURE_LOCATION "$LOCATION"
azd env set AZURE_ENV_NAME "$ENV_NAME"

echo "[3/5] Provisioning infrastructure + deploying app..."
azd up

echo "[4/5] Reading deployment outputs..."
RG_NAME="$(azd env get-values --output json | node -e 'let s=""; process.stdin.on("data",d=>s+=d).on("end",()=>{console.log(JSON.parse(s).AZURE_RESOURCE_GROUP||"")})')"
TENANT_ID="$(az account show --query tenantId -o tsv)"
ENDPOINT="$(az cognitiveservices account show -g "$RG_NAME" -n "arqcdr-openai-$ENV_NAME" --query properties.endpoint -o tsv)"
OPENAI_KEY="$(az cognitiveservices account keys list -g "$RG_NAME" -n "arqcdr-openai-$ENV_NAME" --query key1 -o tsv)"
COSMOS_CONN="$(az cosmosdb keys list -g "$RG_NAME" -n "arqcdr-cosmos-$ENV_NAME" --type connection-strings --query "connectionStrings[0].connectionString" -o tsv)"
STORAGE_NAME="arqcdrst$ENV_NAME"
STORAGE_KEY="$(az storage account keys list -g "$RG_NAME" -n "$STORAGE_NAME" --query "[0].value" -o tsv)"
STORAGE_CONN="DefaultEndpointsProtocol=https;AccountName=$STORAGE_NAME;AccountKey=$STORAGE_KEY;EndpointSuffix=core.windows.net"

echo "[5/5] Writing .env.local..."
cat > .env.local <<EOF
# Generated by scripts/setup-azure.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NODE_ENV=development
PORT=3000
PUBLIC_BASE_URL=http://localhost:3000

AZURE_COSMOS_CONNECTION_STRING=$COSMOS_CONN
AZURE_COSMOS_DATABASE=arqcdr-db
AZURE_COSMOS_CONTAINER=projects

AZURE_STORAGE_CONNECTION_STRING=$STORAGE_CONN
AZURE_STORAGE_CONTAINER=exports

AZURE_OPENAI_ENDPOINT=$ENDPOINT
AZURE_OPENAI_API_KEY=$OPENAI_KEY
AZURE_OPENAI_DEPLOYMENT=gpt-4o-mini
AZURE_OPENAI_API_VERSION=2024-10-21

AZURE_TENANT_ID=$TENANT_ID
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=
AZURE_REDIRECT_URI=http://localhost:3000/auth/callback

VITE_AZURE_TENANT_ID=$TENANT_ID
VITE_AZURE_CLIENT_ID=
VITE_AZURE_REDIRECT_URI=http://localhost:3000
EOF

echo ""
echo "Done. Provisioned in resource group '$RG_NAME'."
echo "Next: register an Entra ID app and fill AZURE_CLIENT_ID / VITE_AZURE_CLIENT_ID in .env.local."
